# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: generic

os: osx

env:
  matrix:
    
    - CONDA_PERL=5.20.3.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "BNQIe9nYPU9P6xu53ApNNSfFevxCqbWynMhzJX2Jf/fPV/0ahf/2ZERr6NMU+F9K0IikmgwN+abgS80zzNxLiWgKMHJbsap9raaK1ArD9Vfrh0fF0DrXBCk6+LiyOMDs7FitwoGFQ0YUAUTmnzqcPbe/8GL+PiHcGKNOfMiY3aokA7QACUU/zuCj87dBdOKocMuvb8Ra+1asMShB8FMAnYqyQUP/98vFTYt2s/DdclLudIp0joOvpvztHL+ghJ8pXzXpmuLVp6afuSOd0Mjc/Dl5elSRrGVRiGBpe5kqYTgT7gvJz/MXFjqiWBsrj/CopforglWt+gZqZn6m2G8ylwQCFA4x74caL1olHGMgkniDmG/9EHSnnQCGOWfaZAuZ1s2pv5cdZeHbXtICK5+10DDKXGDadUR44o3jg1fRCU2ygjXH2MqdNK5xkL7PiA1SUNKGUxxkUGilGCQ3J+a75i4F9j+s5uSwQpK7nE/s2mqetntTs+0bgbu48hxcw3zP+0h9bm8pj+AyN8SHtTVxDni/Yvsj1ArMF8NvADnRtyW6CwQVArQDu+p1Qb9b91kaTGB3eQSvAbs4npN+jwQMAoDtK44XLn2uFmSgcQHxkgCAXKzlvKH0eXHCLrbk3xizYbN4xukmuNl8+0Vpzs+7tcszqPwxmCDztLF+uXN5QJs="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe gorgoncryoem --channel=dependency
