travis:
  secure:
    BINSTAR_TOKEN: BNQIe9nYPU9P6xu53ApNNSfFevxCqbWynMhzJX2Jf/fPV/0ahf/2ZERr6NMU+F9K0IikmgwN+abgS80zzNxLiWgKMHJbsap9raaK1ArD9Vfrh0fF0DrXBCk6+LiyOMDs7FitwoGFQ0YUAUTmnzqcPbe/8GL+PiHcGKNOfMiY3aokA7QACUU/zuCj87dBdOKocMuvb8Ra+1asMShB8FMAnYqyQUP/98vFTYt2s/DdclLudIp0joOvpvztHL+ghJ8pXzXpmuLVp6afuSOd0Mjc/Dl5elSRrGVRiGBpe5kqYTgT7gvJz/MXFjqiWBsrj/CopforglWt+gZqZn6m2G8ylwQCFA4x74caL1olHGMgkniDmG/9EHSnnQCGOWfaZAuZ1s2pv5cdZeHbXtICK5+10DDKXGDadUR44o3jg1fRCU2ygjXH2MqdNK5xkL7PiA1SUNKGUxxkUGilGCQ3J+a75i4F9j+s5uSwQpK7nE/s2mqetntTs+0bgbu48hxcw3zP+0h9bm8pj+AyN8SHtTVxDni/Yvsj1ArMF8NvADnRtyW6CwQVArQDu+p1Qb9b91kaTGB3eQSvAbs4npN+jwQMAoDtK44XLn2uFmSgcQHxkgCAXKzlvKH0eXHCLrbk3xizYbN4xukmuNl8+0Vpzs+7tcszqPwxmCDztLF+uXN5QJs=
appveyor:
  secure:
    BINSTAR_TOKEN: 4ef5IUakGqqw7GSfuIp93Q4MdAC1VnweE1kFVAOUs6ThPDQWBqNpGaq6ZuEbX1FL
